# ============================================
# Prometheus Configuration for 12306-MCP-Server
# ============================================

global:
  # 抓取间隔
  scrape_interval: 15s
  
  # 评估规则的间隔
  evaluation_interval: 15s
  
  # 附加到所有时间序列的标签
  external_labels:
    cluster: 'main'
    environment: 'production'

# ============================================
# 告警管理器配置
# ============================================
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'

# ============================================
# 规则文件
# ============================================
rule_files:
  - 'rules/*.yml'

# ============================================
# 抓取配置
# ============================================
scrape_configs:
  # ------------------------------------------
  # Prometheus 自身
  # ------------------------------------------
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ------------------------------------------
  # 12306-MCP-Server
  # ------------------------------------------
  - job_name: '12306-mcp-server'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['12306-mcp:9090']
        labels:
          service: '12306-mcp'
          instance: 'main'
    
    # 指标重标签
    metric_relabel_configs:
      # 删除不需要的指标
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop

  # ------------------------------------------
  # Node Exporter (可选 - 系统指标)
  # ------------------------------------------
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

# ============================================
# 远程写入配置 (可选)
# ============================================
# remote_write:
#   - url: "http://remote-prometheus:9090/api/v1/write"
#     queue_config:
#       capacity: 10000
#       max_shards: 10
#       min_shards: 1
#       max_samples_per_send: 1000
#       batch_send_deadline: 5s
#       min_backoff: 30ms
#       max_backoff: 100ms

# ============================================
# 远程读取配置 (可选)
# ============================================
# remote_read:
#   - url: "http://remote-prometheus:9090/api/v1/read"